services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/geopointsdb
      - TEST_DATABASE_URL=postgresql://postgres:postgres@db:5432/geopoints_test
      - API_TITLE=GeoPoints API
      - API_VERSION=0.1.0
      - DEBUG=False
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - geopoints_net  # Changed network name

  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=geopointsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - geopoints_net  # Changed network name

  db-test:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=geopointsdb
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - geopoints_net  # Changed network name

volumes:
  postgres_data:
  postgres_test_data:

networks:
  geopoints_net:    # Corrected network definition
    driver: bridge